<#import "blocks/common.ftlh" as c>
<#import "blocks/auth.ftlh" as a>
<@c.page>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.5/examples/sign-in/signin.css" />
    <title>Регистрация</title>
</head>
<@a.register />
</@c.page>